// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"
	domain "webook/reward/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockRewardCache is a mock of RewardCache interface.
type MockRewardCache struct {
	ctrl     *gomock.Controller
	recorder *MockRewardCacheMockRecorder
}

// MockRewardCacheMockRecorder is the mock recorder for MockRewardCache.
type MockRewardCacheMockRecorder struct {
	mock *MockRewardCache
}

// NewMockRewardCache creates a new mock instance.
func NewMockRewardCache(ctrl *gomock.Controller) *MockRewardCache {
	mock := &MockRewardCache{ctrl: ctrl}
	mock.recorder = &MockRewardCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardCache) EXPECT() *MockRewardCacheMockRecorder {
	return m.recorder
}

// CachedCodeURL mocks base method.
func (m *MockRewardCache) CachedCodeURL(ctx context.Context, cu domain.CodeURL, r domain.Reward) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachedCodeURL", ctx, cu, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// CachedCodeURL indicates an expected call of CachedCodeURL.
func (mr *MockRewardCacheMockRecorder) CachedCodeURL(ctx, cu, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachedCodeURL", reflect.TypeOf((*MockRewardCache)(nil).CachedCodeURL), ctx, cu, r)
}

// GetCachedCodeURL mocks base method.
func (m *MockRewardCache) GetCachedCodeURL(ctx context.Context, r domain.Reward) (domain.CodeURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedCodeURL", ctx, r)
	ret0, _ := ret[0].(domain.CodeURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedCodeURL indicates an expected call of GetCachedCodeURL.
func (mr *MockRewardCacheMockRecorder) GetCachedCodeURL(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedCodeURL", reflect.TypeOf((*MockRewardCache)(nil).GetCachedCodeURL), ctx, r)
}
