// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/payment/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockLocalMsgDAO is a mock of LocalMsgDAO interface.
type MockLocalMsgDAO struct {
	ctrl     *gomock.Controller
	recorder *MockLocalMsgDAOMockRecorder
}

// MockLocalMsgDAOMockRecorder is the mock recorder for MockLocalMsgDAO.
type MockLocalMsgDAOMockRecorder struct {
	mock *MockLocalMsgDAO
}

// NewMockLocalMsgDAO creates a new mock instance.
func NewMockLocalMsgDAO(ctrl *gomock.Controller) *MockLocalMsgDAO {
	mock := &MockLocalMsgDAO{ctrl: ctrl}
	mock.recorder = &MockLocalMsgDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalMsgDAO) EXPECT() *MockLocalMsgDAOMockRecorder {
	return m.recorder
}

// AddMsg mocks base method.
func (m *MockLocalMsgDAO) AddMsg(ctx context.Context, msg dao.Msg) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMsg", ctx, msg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMsg indicates an expected call of AddMsg.
func (mr *MockLocalMsgDAOMockRecorder) AddMsg(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMsg", reflect.TypeOf((*MockLocalMsgDAO)(nil).AddMsg), ctx, msg)
}

// UpdateStatus mocks base method.
func (m *MockLocalMsgDAO) UpdateStatus(ctx context.Context, id int64, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockLocalMsgDAOMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockLocalMsgDAO)(nil).UpdateStatus), ctx, id, status)
}
