// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	time "time"
	domain "webook/payment/domain"
	dao "webook/payment/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentDAO is a mock of PaymentDAO interface.
type MockPaymentDAO struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentDAOMockRecorder
}

// MockPaymentDAOMockRecorder is the mock recorder for MockPaymentDAO.
type MockPaymentDAOMockRecorder struct {
	mock *MockPaymentDAO
}

// NewMockPaymentDAO creates a new mock instance.
func NewMockPaymentDAO(ctrl *gomock.Controller) *MockPaymentDAO {
	mock := &MockPaymentDAO{ctrl: ctrl}
	mock.recorder = &MockPaymentDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentDAO) EXPECT() *MockPaymentDAOMockRecorder {
	return m.recorder
}

// FindExpiredPayment mocks base method.
func (m *MockPaymentDAO) FindExpiredPayment(ctx context.Context, limit, offset int, t time.Time) ([]dao.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpiredPayment", ctx, limit, offset, t)
	ret0, _ := ret[0].([]dao.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpiredPayment indicates an expected call of FindExpiredPayment.
func (mr *MockPaymentDAOMockRecorder) FindExpiredPayment(ctx, limit, offset, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpiredPayment", reflect.TypeOf((*MockPaymentDAO)(nil).FindExpiredPayment), ctx, limit, offset, t)
}

// GetPayment mocks base method.
func (m *MockPaymentDAO) GetPayment(ctx context.Context, bizTradeNo string) (dao.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", ctx, bizTradeNo)
	ret0, _ := ret[0].(dao.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockPaymentDAOMockRecorder) GetPayment(ctx, bizTradeNo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockPaymentDAO)(nil).GetPayment), ctx, bizTradeNo)
}

// Insert mocks base method.
func (m *MockPaymentDAO) Insert(ctx context.Context, pmt dao.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, pmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockPaymentDAOMockRecorder) Insert(ctx, pmt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockPaymentDAO)(nil).Insert), ctx, pmt)
}

// UpdateTxnIDAndStatus mocks base method.
func (m *MockPaymentDAO) UpdateTxnIDAndStatus(ctx context.Context, bizTradeNo, txnID string, status domain.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTxnIDAndStatus", ctx, bizTradeNo, txnID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTxnIDAndStatus indicates an expected call of UpdateTxnIDAndStatus.
func (mr *MockPaymentDAOMockRecorder) UpdateTxnIDAndStatus(ctx, bizTradeNo, txnID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTxnIDAndStatus", reflect.TypeOf((*MockPaymentDAO)(nil).UpdateTxnIDAndStatus), ctx, bizTradeNo, txnID, status)
}
