// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/tag/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockTagDAO is a mock of TagDAO interface.
type MockTagDAO struct {
	ctrl     *gomock.Controller
	recorder *MockTagDAOMockRecorder
}

// MockTagDAOMockRecorder is the mock recorder for MockTagDAO.
type MockTagDAOMockRecorder struct {
	mock *MockTagDAO
}

// NewMockTagDAO creates a new mock instance.
func NewMockTagDAO(ctrl *gomock.Controller) *MockTagDAO {
	mock := &MockTagDAO{ctrl: ctrl}
	mock.recorder = &MockTagDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagDAO) EXPECT() *MockTagDAOMockRecorder {
	return m.recorder
}

// CreateTag mocks base method.
func (m *MockTagDAO) CreateTag(ctx context.Context, tag dao.Tag) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, tag)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockTagDAOMockRecorder) CreateTag(ctx, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockTagDAO)(nil).CreateTag), ctx, tag)
}

// CreateTagBiz mocks base method.
func (m *MockTagDAO) CreateTagBiz(ctx context.Context, tagBiz []dao.TagBiz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTagBiz", ctx, tagBiz)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTagBiz indicates an expected call of CreateTagBiz.
func (mr *MockTagDAOMockRecorder) CreateTagBiz(ctx, tagBiz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagBiz", reflect.TypeOf((*MockTagDAO)(nil).CreateTagBiz), ctx, tagBiz)
}

// GetTags mocks base method.
func (m *MockTagDAO) GetTags(ctx context.Context, limit, offset int) ([]dao.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx, limit, offset)
	ret0, _ := ret[0].([]dao.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockTagDAOMockRecorder) GetTags(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockTagDAO)(nil).GetTags), ctx, limit, offset)
}

// GetTagsByBiz mocks base method.
func (m *MockTagDAO) GetTagsByBiz(ctx context.Context, uid int64, biz string, bizId int64) ([]dao.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByBiz", ctx, uid, biz, bizId)
	ret0, _ := ret[0].([]dao.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByBiz indicates an expected call of GetTagsByBiz.
func (mr *MockTagDAOMockRecorder) GetTagsByBiz(ctx, uid, biz, bizId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByBiz", reflect.TypeOf((*MockTagDAO)(nil).GetTagsByBiz), ctx, uid, biz, bizId)
}

// GetTagsById mocks base method.
func (m *MockTagDAO) GetTagsById(ctx context.Context, ids []int64) ([]dao.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsById", ctx, ids)
	ret0, _ := ret[0].([]dao.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsById indicates an expected call of GetTagsById.
func (mr *MockTagDAOMockRecorder) GetTagsById(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsById", reflect.TypeOf((*MockTagDAO)(nil).GetTagsById), ctx, ids)
}

// GetTagsByUid mocks base method.
func (m *MockTagDAO) GetTagsByUid(ctx context.Context, uid int64) ([]dao.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByUid", ctx, uid)
	ret0, _ := ret[0].([]dao.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByUid indicates an expected call of GetTagsByUid.
func (mr *MockTagDAOMockRecorder) GetTagsByUid(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByUid", reflect.TypeOf((*MockTagDAO)(nil).GetTagsByUid), ctx, uid)
}
