// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/follow/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockFollowRelationDAO is a mock of FollowRelationDAO interface.
type MockFollowRelationDAO struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRelationDAOMockRecorder
}

// MockFollowRelationDAOMockRecorder is the mock recorder for MockFollowRelationDAO.
type MockFollowRelationDAOMockRecorder struct {
	mock *MockFollowRelationDAO
}

// NewMockFollowRelationDAO creates a new mock instance.
func NewMockFollowRelationDAO(ctrl *gomock.Controller) *MockFollowRelationDAO {
	mock := &MockFollowRelationDAO{ctrl: ctrl}
	mock.recorder = &MockFollowRelationDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRelationDAO) EXPECT() *MockFollowRelationDAOMockRecorder {
	return m.recorder
}

// CountFollowee mocks base method.
func (m *MockFollowRelationDAO) CountFollowee(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowee", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowee indicates an expected call of CountFollowee.
func (mr *MockFollowRelationDAOMockRecorder) CountFollowee(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowee", reflect.TypeOf((*MockFollowRelationDAO)(nil).CountFollowee), ctx, uid)
}

// CountFollower mocks base method.
func (m *MockFollowRelationDAO) CountFollower(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollower", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollower indicates an expected call of CountFollower.
func (mr *MockFollowRelationDAOMockRecorder) CountFollower(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollower", reflect.TypeOf((*MockFollowRelationDAO)(nil).CountFollower), ctx, uid)
}

// CreateFollowRelation mocks base method.
func (m *MockFollowRelationDAO) CreateFollowRelation(ctx context.Context, c dao.FollowRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFollowRelation", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFollowRelation indicates an expected call of CreateFollowRelation.
func (mr *MockFollowRelationDAOMockRecorder) CreateFollowRelation(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFollowRelation", reflect.TypeOf((*MockFollowRelationDAO)(nil).CreateFollowRelation), ctx, c)
}

// FollowRelationDetail mocks base method.
func (m *MockFollowRelationDAO) FollowRelationDetail(ctx context.Context, follower, followee int64) (dao.FollowRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowRelationDetail", ctx, follower, followee)
	ret0, _ := ret[0].(dao.FollowRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowRelationDetail indicates an expected call of FollowRelationDetail.
func (mr *MockFollowRelationDAOMockRecorder) FollowRelationDetail(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowRelationDetail", reflect.TypeOf((*MockFollowRelationDAO)(nil).FollowRelationDetail), ctx, follower, followee)
}

// FollowRelationList mocks base method.
func (m *MockFollowRelationDAO) FollowRelationList(ctx context.Context, follower int64, limit, offset int) ([]dao.FollowRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowRelationList", ctx, follower, limit, offset)
	ret0, _ := ret[0].([]dao.FollowRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowRelationList indicates an expected call of FollowRelationList.
func (mr *MockFollowRelationDAOMockRecorder) FollowRelationList(ctx, follower, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowRelationList", reflect.TypeOf((*MockFollowRelationDAO)(nil).FollowRelationList), ctx, follower, limit, offset)
}

// UpdateStatus mocks base method.
func (m *MockFollowRelationDAO) UpdateStatus(ctx context.Context, followee, follower int64, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, followee, follower, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFollowRelationDAOMockRecorder) UpdateStatus(ctx, followee, follower, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFollowRelationDAO)(nil).UpdateStatus), ctx, followee, follower, status)
}
