// Code generated by MockGen. DO NOT EDIT.
// Source: ./history.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockHistoryRecordRepository is a mock of HistoryRecordRepository interface.
type MockHistoryRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryRecordRepositoryMockRecorder
}

// MockHistoryRecordRepositoryMockRecorder is the mock recorder for MockHistoryRecordRepository.
type MockHistoryRecordRepositoryMockRecorder struct {
	mock *MockHistoryRecordRepository
}

// NewMockHistoryRecordRepository creates a new mock instance.
func NewMockHistoryRecordRepository(ctrl *gomock.Controller) *MockHistoryRecordRepository {
	mock := &MockHistoryRecordRepository{ctrl: ctrl}
	mock.recorder = &MockHistoryRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryRecordRepository) EXPECT() *MockHistoryRecordRepositoryMockRecorder {
	return m.recorder
}

// AddRecord mocks base method.
func (m *MockHistoryRecordRepository) AddRecord(ctx context.Context, record domain.HistoryRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRecord indicates an expected call of AddRecord.
func (mr *MockHistoryRecordRepositoryMockRecorder) AddRecord(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockHistoryRecordRepository)(nil).AddRecord), ctx, record)
}
