// Code generated by MockGen. DO NOT EDIT.
// Source: ./ranking.go

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"
	domain "webook/ranking/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockRankingCache is a mock of RankingCache interface.
type MockRankingCache struct {
	ctrl     *gomock.Controller
	recorder *MockRankingCacheMockRecorder
}

// MockRankingCacheMockRecorder is the mock recorder for MockRankingCache.
type MockRankingCacheMockRecorder struct {
	mock *MockRankingCache
}

// NewMockRankingCache creates a new mock instance.
func NewMockRankingCache(ctrl *gomock.Controller) *MockRankingCache {
	mock := &MockRankingCache{ctrl: ctrl}
	mock.recorder = &MockRankingCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingCache) EXPECT() *MockRankingCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRankingCache) Get(ctx context.Context) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRankingCacheMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRankingCache)(nil).Get), ctx)
}

// Set mocks base method.
func (m *MockRankingCache) Set(ctx context.Context, articles []domain.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, articles)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRankingCacheMockRecorder) Set(ctx, articles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRankingCache)(nil).Set), ctx, articles)
}
