// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/comment/grpc"
	"webook/comment/ioc"
	"webook/comment/repository"
	"webook/comment/repository/dao"
	"webook/comment/service"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	commentDAO := dao.NewCommentGormDAO(db)
	commentRepository := repository.NewCachedCommentRepository(commentDAO, logger)
	commentService := service.NewCommentService(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	server := ioc.InitGrpcxServer(commentServiceServer, logger)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var svcProviderSet = wire.NewSet(dao.NewCommentGormDAO, repository.NewCachedCommentRepository, service.NewCommentService, grpc.NewGrpcServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB)
