// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/pkg_local/wego"
	"webook/reward/grpc"
	"webook/reward/ioc"
	"webook/reward/repository"
	"webook/reward/repository/cache"
	"webook/reward/repository/dao"
	"webook/reward/service"
)

// Injectors from wire.go:

func Init() *wego.App {
	client := ioc.InitEtcdClient()
	wechatPaymentServiceClient := ioc.InitPaymentClient(client)
	db := ioc.InitDB()
	rewardDAO := dao.NewRewardGormDAO(db)
	cmdable := ioc.InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	logger := ioc.InitLogger()
	accountServiceClient := ioc.InitAccountClient(client)
	rewardService := service.NewWechatNativeRewardService(wechatPaymentServiceClient, rewardRepository, logger, accountServiceClient)
	rewardServiceServer := grpc.NewRewardServiceServer(rewardService)
	server := ioc.InitGrpcxServer(rewardServiceServer, client, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitRedis)
