// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	domain "webook/tag/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockTagService is a mock of TagService interface.
type MockTagService struct {
	ctrl     *gomock.Controller
	recorder *MockTagServiceMockRecorder
}

// MockTagServiceMockRecorder is the mock recorder for MockTagService.
type MockTagServiceMockRecorder struct {
	mock *MockTagService
}

// NewMockTagService creates a new mock instance.
func NewMockTagService(ctrl *gomock.Controller) *MockTagService {
	mock := &MockTagService{ctrl: ctrl}
	mock.recorder = &MockTagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagService) EXPECT() *MockTagServiceMockRecorder {
	return m.recorder
}

// AttachTags mocks base method.
func (m *MockTagService) AttachTags(ctx context.Context, uid int64, biz string, bizId int64, tags []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachTags", ctx, uid, biz, bizId, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachTags indicates an expected call of AttachTags.
func (mr *MockTagServiceMockRecorder) AttachTags(ctx, uid, biz, bizId, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachTags", reflect.TypeOf((*MockTagService)(nil).AttachTags), ctx, uid, biz, bizId, tags)
}

// CreateTag mocks base method.
func (m *MockTagService) CreateTag(ctx context.Context, uid int64, name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, uid, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockTagServiceMockRecorder) CreateTag(ctx, uid, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockTagService)(nil).CreateTag), ctx, uid, name)
}

// GetBizTags mocks base method.
func (m *MockTagService) GetBizTags(ctx context.Context, uid int64, biz string, bizId int64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBizTags", ctx, uid, biz, bizId)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBizTags indicates an expected call of GetBizTags.
func (mr *MockTagServiceMockRecorder) GetBizTags(ctx, uid, biz, bizId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBizTags", reflect.TypeOf((*MockTagService)(nil).GetBizTags), ctx, uid, biz, bizId)
}

// GetTags mocks base method.
func (m *MockTagService) GetTags(ctx context.Context, uid int64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx, uid)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockTagServiceMockRecorder) GetTags(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockTagService)(nil).GetTags), ctx, uid)
}
