// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/ranking/grpc"
	"webook/ranking/ioc"
	"webook/ranking/repository"
	"webook/ranking/repository/cache"
	"webook/ranking/service"
)

// Injectors from wire.go:

func Init() *App {
	interactiveServiceClient := ioc.InitInterActiveRpcClient()
	articleServiceClient := ioc.InitArticleRpcClient()
	cmdable := ioc.InitRedis()
	rankingCache := cache.NewRankingRedisCache(cmdable)
	rankingRepository := repository.NewCachedRankingRepository(rankingCache)
	rankingService := service.NewBatchRankingService(interactiveServiceClient, articleServiceClient, rankingRepository)
	rankingServiceServer := grpc.NewRankingServiceServer(rankingService)
	client := ioc.InitEtcdClient()
	logger := ioc.InitLogger()
	server := ioc.InitGrpcServer(rankingServiceServer, client, logger)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(cache.NewRankingLocalCache, cache.NewRankingRedisCache, repository.NewCachedRankingRepository, service.NewBatchRankingService)

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitInterActiveRpcClient, ioc.InitArticleRpcClient, ioc.InitEtcdClient, ioc.InitLogger)
