// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	domain "webook/search/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockSyncService is a mock of SyncService interface.
type MockSyncService struct {
	ctrl     *gomock.Controller
	recorder *MockSyncServiceMockRecorder
}

// MockSyncServiceMockRecorder is the mock recorder for MockSyncService.
type MockSyncServiceMockRecorder struct {
	mock *MockSyncService
}

// NewMockSyncService creates a new mock instance.
func NewMockSyncService(ctrl *gomock.Controller) *MockSyncService {
	mock := &MockSyncService{ctrl: ctrl}
	mock.recorder = &MockSyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncService) EXPECT() *MockSyncServiceMockRecorder {
	return m.recorder
}

// InputAny mocks base method.
func (m *MockSyncService) InputAny(ctx context.Context, indexName, docId, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputAny", ctx, indexName, docId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// InputAny indicates an expected call of InputAny.
func (mr *MockSyncServiceMockRecorder) InputAny(ctx, indexName, docId, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputAny", reflect.TypeOf((*MockSyncService)(nil).InputAny), ctx, indexName, docId, data)
}

// InputArticle mocks base method.
func (m *MockSyncService) InputArticle(ctx context.Context, article domain.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputArticle", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// InputArticle indicates an expected call of InputArticle.
func (mr *MockSyncServiceMockRecorder) InputArticle(ctx, article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputArticle", reflect.TypeOf((*MockSyncService)(nil).InputArticle), ctx, article)
}

// InputUser mocks base method.
func (m *MockSyncService) InputUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// InputUser indicates an expected call of InputUser.
func (mr *MockSyncServiceMockRecorder) InputUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputUser", reflect.TypeOf((*MockSyncService)(nil).InputUser), ctx, user)
}
