// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	domain "webook/follow/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockFollowRelationService is a mock of FollowRelationService interface.
type MockFollowRelationService struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRelationServiceMockRecorder
}

// MockFollowRelationServiceMockRecorder is the mock recorder for MockFollowRelationService.
type MockFollowRelationServiceMockRecorder struct {
	mock *MockFollowRelationService
}

// NewMockFollowRelationService creates a new mock instance.
func NewMockFollowRelationService(ctrl *gomock.Controller) *MockFollowRelationService {
	mock := &MockFollowRelationService{ctrl: ctrl}
	mock.recorder = &MockFollowRelationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRelationService) EXPECT() *MockFollowRelationServiceMockRecorder {
	return m.recorder
}

// CancelFollow mocks base method.
func (m *MockFollowRelationService) CancelFollow(ctx context.Context, follower, followee int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelFollow", ctx, follower, followee)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelFollow indicates an expected call of CancelFollow.
func (mr *MockFollowRelationServiceMockRecorder) CancelFollow(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelFollow", reflect.TypeOf((*MockFollowRelationService)(nil).CancelFollow), ctx, follower, followee)
}

// Follow mocks base method.
func (m *MockFollowRelationService) Follow(ctx context.Context, follower, followee int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, follower, followee)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowRelationServiceMockRecorder) Follow(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowRelationService)(nil).Follow), ctx, follower, followee)
}

// FollowInfo mocks base method.
func (m *MockFollowRelationService) FollowInfo(ctx context.Context, follower, followee int64) (domain.FollowRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowInfo", ctx, follower, followee)
	ret0, _ := ret[0].(domain.FollowRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowInfo indicates an expected call of FollowInfo.
func (mr *MockFollowRelationServiceMockRecorder) FollowInfo(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowInfo", reflect.TypeOf((*MockFollowRelationService)(nil).FollowInfo), ctx, follower, followee)
}

// GetFollowStatic mocks base method.
func (m *MockFollowRelationService) GetFollowStatic(ctx context.Context, followee int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowStatic", ctx, followee)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowStatic indicates an expected call of GetFollowStatic.
func (mr *MockFollowRelationServiceMockRecorder) GetFollowStatic(ctx, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowStatic", reflect.TypeOf((*MockFollowRelationService)(nil).GetFollowStatic), ctx, followee)
}

// GetFollowee mocks base method.
func (m *MockFollowRelationService) GetFollowee(ctx context.Context, follower int64, limit, offset int) ([]domain.FollowRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowee", ctx, follower, limit, offset)
	ret0, _ := ret[0].([]domain.FollowRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowee indicates an expected call of GetFollowee.
func (mr *MockFollowRelationServiceMockRecorder) GetFollowee(ctx, follower, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowee", reflect.TypeOf((*MockFollowRelationService)(nil).GetFollowee), ctx, follower, limit, offset)
}

// GetFollower mocks base method.
func (m *MockFollowRelationService) GetFollower(ctx context.Context, follower int64, limit, offset int) ([]domain.FollowRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollower", ctx, follower, limit, offset)
	ret0, _ := ret[0].([]domain.FollowRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollower indicates an expected call of GetFollower.
func (mr *MockFollowRelationServiceMockRecorder) GetFollower(ctx, follower, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollower", reflect.TypeOf((*MockFollowRelationService)(nil).GetFollower), ctx, follower, limit, offset)
}
