// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/pkg_local/wego"
	"webook/tag/grpc"
	"webook/tag/ioc"
	"webook/tag/repository/cache"
	"webook/tag/repository/dao"
	"webook/tag/service"
)

// Injectors from wire.go:

func Init() *wego.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	tagDAO := dao.NewGormTagDAO(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	tagRepository := ioc.InitRepository(tagDAO, tagCache, logger)
	client := ioc.InitKafka()
	producer := ioc.InitProducer(client)
	tagService := service.NewTagService(tagRepository, logger, producer)
	tagServiceServer := grpc.NewTagGrpcServer(tagService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(tagServiceServer, clientv3Client, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitLogger, ioc.InitDB, ioc.InitEtcdClient, ioc.InitKafka)
