// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/bff/ioc"
	"webook/bff/web"
	"webook/bff/web/jwt"
	"webook/pkg_local/wego"
)

// Injectors from wire.go:

func InitApp() *wego.App {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	client := ioc.InitEtcdClient()
	userServiceClient := ioc.InitUserClient(client)
	codeServiceClient := ioc.InitCodeClient(client)
	userHandler := web.NewUserHandler(logger, userServiceClient, codeServiceClient, handler)
	articleServiceClient := ioc.InitArticleClient(client)
	interactiveServiceClient := ioc.InitIntrClient(client)
	rewardServiceClient := ioc.InitRewardClient(client)
	articleHandler := web.NewArticleHandler(logger, articleServiceClient, interactiveServiceClient, rewardServiceClient)
	rewardHandler := web.NewRewardHandler(rewardServiceClient)
	server := ioc.InitGinServer(logger, handler, userHandler, articleHandler, rewardHandler)
	app := &wego.App{
		WebServer: server,
	}
	return app
}
