// Code generated by MockGen. DO NOT EDIT.
// Source: ./feed_event.go

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFeedEventCache is a mock of FeedEventCache interface.
type MockFeedEventCache struct {
	ctrl     *gomock.Controller
	recorder *MockFeedEventCacheMockRecorder
}

// MockFeedEventCacheMockRecorder is the mock recorder for MockFeedEventCache.
type MockFeedEventCacheMockRecorder struct {
	mock *MockFeedEventCache
}

// NewMockFeedEventCache creates a new mock instance.
func NewMockFeedEventCache(ctrl *gomock.Controller) *MockFeedEventCache {
	mock := &MockFeedEventCache{ctrl: ctrl}
	mock.recorder = &MockFeedEventCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedEventCache) EXPECT() *MockFeedEventCacheMockRecorder {
	return m.recorder
}

// GetFollowees mocks base method.
func (m *MockFeedEventCache) GetFollowees(ctx context.Context, follower int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowees", ctx, follower)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowees indicates an expected call of GetFollowees.
func (mr *MockFeedEventCacheMockRecorder) GetFollowees(ctx, follower interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowees", reflect.TypeOf((*MockFeedEventCache)(nil).GetFollowees), ctx, follower)
}

// SetFollowees mocks base method.
func (m *MockFeedEventCache) SetFollowees(ctx context.Context, follower int64, followees []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFollowees", ctx, follower, followees)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFollowees indicates an expected call of SetFollowees.
func (mr *MockFeedEventCacheMockRecorder) SetFollowees(ctx, follower, followees interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFollowees", reflect.TypeOf((*MockFeedEventCache)(nil).SetFollowees), ctx, follower, followees)
}
