// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/code/grpc"
	"webook/code/ioc"
	"webook/code/repository"
	"webook/code/repository/cache"
	"webook/code/service"
)

// Injectors from wire.go:

func Init() *App {
	cmdable := ioc.InitRedis()
	logger := ioc.InitLogger()
	codeCache := cache.NewRedisCodeCache(cmdable, logger)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	smsServiceClient := ioc.InitSmsRpcClient()
	codeService := service.NewSMSCodeService(codeRepository, smsServiceClient)
	codeServiceServer := grpc.NewCodeServiceServer(codeService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(codeServiceServer, client, logger)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitLogger, ioc.InitEtcdClient)
