// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/comment/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockCommentDAO is a mock of CommentDAO interface.
type MockCommentDAO struct {
	ctrl     *gomock.Controller
	recorder *MockCommentDAOMockRecorder
}

// MockCommentDAOMockRecorder is the mock recorder for MockCommentDAO.
type MockCommentDAOMockRecorder struct {
	mock *MockCommentDAO
}

// NewMockCommentDAO creates a new mock instance.
func NewMockCommentDAO(ctrl *gomock.Controller) *MockCommentDAO {
	mock := &MockCommentDAO{ctrl: ctrl}
	mock.recorder = &MockCommentDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentDAO) EXPECT() *MockCommentDAOMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCommentDAO) Delete(ctx context.Context, u dao.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentDAOMockRecorder) Delete(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentDAO)(nil).Delete), ctx, u)
}

// FindByBiz mocks base method.
func (m *MockCommentDAO) FindByBiz(ctx context.Context, biz string, bizId, minId, limit int64) ([]dao.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBiz", ctx, biz, bizId, minId, limit)
	ret0, _ := ret[0].([]dao.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBiz indicates an expected call of FindByBiz.
func (mr *MockCommentDAOMockRecorder) FindByBiz(ctx, biz, bizId, minId, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBiz", reflect.TypeOf((*MockCommentDAO)(nil).FindByBiz), ctx, biz, bizId, minId, limit)
}

// FindCommentList mocks base method.
func (m *MockCommentDAO) FindCommentList(ctx context.Context, u dao.Comment) ([]dao.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCommentList", ctx, u)
	ret0, _ := ret[0].([]dao.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCommentList indicates an expected call of FindCommentList.
func (mr *MockCommentDAOMockRecorder) FindCommentList(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCommentList", reflect.TypeOf((*MockCommentDAO)(nil).FindCommentList), ctx, u)
}

// FindOneByIds mocks base method.
func (m *MockCommentDAO) FindOneByIds(ctx context.Context, ids []int64) ([]dao.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByIds", ctx, ids)
	ret0, _ := ret[0].([]dao.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByIds indicates an expected call of FindOneByIds.
func (mr *MockCommentDAOMockRecorder) FindOneByIds(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByIds", reflect.TypeOf((*MockCommentDAO)(nil).FindOneByIds), ctx, ids)
}

// FindRepliesByParentId mocks base method.
func (m *MockCommentDAO) FindRepliesByParentId(ctx context.Context, parentId, limit, offset int64) ([]dao.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRepliesByParentId", ctx, parentId, limit, offset)
	ret0, _ := ret[0].([]dao.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRepliesByParentId indicates an expected call of FindRepliesByParentId.
func (mr *MockCommentDAOMockRecorder) FindRepliesByParentId(ctx, parentId, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRepliesByParentId", reflect.TypeOf((*MockCommentDAO)(nil).FindRepliesByParentId), ctx, parentId, limit, offset)
}

// FindRepliesByRootId mocks base method.
func (m *MockCommentDAO) FindRepliesByRootId(ctx context.Context, rootId, id, limit int64) ([]dao.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRepliesByRootId", ctx, rootId, id, limit)
	ret0, _ := ret[0].([]dao.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRepliesByRootId indicates an expected call of FindRepliesByRootId.
func (mr *MockCommentDAOMockRecorder) FindRepliesByRootId(ctx, rootId, id, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRepliesByRootId", reflect.TypeOf((*MockCommentDAO)(nil).FindRepliesByRootId), ctx, rootId, id, limit)
}

// Insert mocks base method.
func (m *MockCommentDAO) Insert(ctx context.Context, u dao.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockCommentDAOMockRecorder) Insert(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCommentDAO)(nil).Insert), ctx, u)
}
