db:
  dsn: "root:123456@tcp(localhost:3306)/)/webook_user"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:2379"

grpc:
  server:
    port: 8105
    etcdTTL: 60
    etcdAddr: "localhost:2379"