// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"
	domain "webook/follow/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockFollowCache is a mock of FollowCache interface.
type MockFollowCache struct {
	ctrl     *gomock.Controller
	recorder *MockFollowCacheMockRecorder
}

// MockFollowCacheMockRecorder is the mock recorder for MockFollowCache.
type MockFollowCacheMockRecorder struct {
	mock *MockFollowCache
}

// NewMockFollowCache creates a new mock instance.
func NewMockFollowCache(ctrl *gomock.Controller) *MockFollowCache {
	mock := &MockFollowCache{ctrl: ctrl}
	mock.recorder = &MockFollowCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowCache) EXPECT() *MockFollowCacheMockRecorder {
	return m.recorder
}

// CancelFollow mocks base method.
func (m *MockFollowCache) CancelFollow(ctx context.Context, follower, followee int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelFollow", ctx, follower, followee)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelFollow indicates an expected call of CancelFollow.
func (mr *MockFollowCacheMockRecorder) CancelFollow(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelFollow", reflect.TypeOf((*MockFollowCache)(nil).CancelFollow), ctx, follower, followee)
}

// Follow mocks base method.
func (m *MockFollowCache) Follow(ctx context.Context, follower, followee int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, follower, followee)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowCacheMockRecorder) Follow(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowCache)(nil).Follow), ctx, follower, followee)
}

// SetStaticsInfo mocks base method.
func (m *MockFollowCache) SetStaticsInfo(ctx context.Context, uid int64, statics domain.FollowStatics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStaticsInfo", ctx, uid, statics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStaticsInfo indicates an expected call of SetStaticsInfo.
func (mr *MockFollowCacheMockRecorder) SetStaticsInfo(ctx, uid, statics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStaticsInfo", reflect.TypeOf((*MockFollowCache)(nil).SetStaticsInfo), ctx, uid, statics)
}

// StaticsInfo mocks base method.
func (m *MockFollowCache) StaticsInfo(ctx context.Context, uid int64) (domain.FollowStatics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StaticsInfo", ctx, uid)
	ret0, _ := ret[0].(domain.FollowStatics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StaticsInfo indicates an expected call of StaticsInfo.
func (mr *MockFollowCacheMockRecorder) StaticsInfo(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StaticsInfo", reflect.TypeOf((*MockFollowCache)(nil).StaticsInfo), ctx, uid)
}
