// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"
	domain "webook/tag/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockTagCache is a mock of TagCache interface.
type MockTagCache struct {
	ctrl     *gomock.Controller
	recorder *MockTagCacheMockRecorder
}

// MockTagCacheMockRecorder is the mock recorder for MockTagCache.
type MockTagCacheMockRecorder struct {
	mock *MockTagCache
}

// NewMockTagCache creates a new mock instance.
func NewMockTagCache(ctrl *gomock.Controller) *MockTagCache {
	mock := &MockTagCache{ctrl: ctrl}
	mock.recorder = &MockTagCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagCache) EXPECT() *MockTagCacheMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockTagCache) Append(ctx context.Context, uid int64, tags ...domain.Tag) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, uid}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Append", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockTagCacheMockRecorder) Append(ctx, uid interface{}, tags ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, uid}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockTagCache)(nil).Append), varargs...)
}

// DelTags mocks base method.
func (m *MockTagCache) DelTags(ctx context.Context, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelTags", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelTags indicates an expected call of DelTags.
func (mr *MockTagCacheMockRecorder) DelTags(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelTags", reflect.TypeOf((*MockTagCache)(nil).DelTags), ctx, uid)
}

// GetTags mocks base method.
func (m *MockTagCache) GetTags(ctx context.Context, uid int64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx, uid)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockTagCacheMockRecorder) GetTags(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockTagCache)(nil).GetTags), ctx, uid)
}
