// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/follow/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockFollowRepository is a mock of FollowRepository interface.
type MockFollowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRepositoryMockRecorder
}

// MockFollowRepositoryMockRecorder is the mock recorder for MockFollowRepository.
type MockFollowRepositoryMockRecorder struct {
	mock *MockFollowRepository
}

// NewMockFollowRepository creates a new mock instance.
func NewMockFollowRepository(ctrl *gomock.Controller) *MockFollowRepository {
	mock := &MockFollowRepository{ctrl: ctrl}
	mock.recorder = &MockFollowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRepository) EXPECT() *MockFollowRepositoryMockRecorder {
	return m.recorder
}

// AddFollowRelation mocks base method.
func (m *MockFollowRepository) AddFollowRelation(ctx context.Context, c domain.FollowRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFollowRelation", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFollowRelation indicates an expected call of AddFollowRelation.
func (mr *MockFollowRepositoryMockRecorder) AddFollowRelation(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFollowRelation", reflect.TypeOf((*MockFollowRepository)(nil).AddFollowRelation), ctx, c)
}

// FollowInfo mocks base method.
func (m *MockFollowRepository) FollowInfo(ctx context.Context, follower, followee int64) (domain.FollowRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowInfo", ctx, follower, followee)
	ret0, _ := ret[0].(domain.FollowRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowInfo indicates an expected call of FollowInfo.
func (mr *MockFollowRepositoryMockRecorder) FollowInfo(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowInfo", reflect.TypeOf((*MockFollowRepository)(nil).FollowInfo), ctx, follower, followee)
}

// GetFollowStatics mocks base method.
func (m *MockFollowRepository) GetFollowStatics(ctx context.Context, uid int64) (domain.FollowStatics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowStatics", ctx, uid)
	ret0, _ := ret[0].(domain.FollowStatics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowStatics indicates an expected call of GetFollowStatics.
func (mr *MockFollowRepositoryMockRecorder) GetFollowStatics(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowStatics", reflect.TypeOf((*MockFollowRepository)(nil).GetFollowStatics), ctx, uid)
}

// GetFollowee mocks base method.
func (m *MockFollowRepository) GetFollowee(ctx context.Context, follower, followee int64, limit, offset int) ([]domain.FollowRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowee", ctx, follower, followee, limit, offset)
	ret0, _ := ret[0].([]domain.FollowRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowee indicates an expected call of GetFollowee.
func (mr *MockFollowRepositoryMockRecorder) GetFollowee(ctx, follower, followee, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowee", reflect.TypeOf((*MockFollowRepository)(nil).GetFollowee), ctx, follower, followee, limit, offset)
}

// InactiveFollowRelation mocks base method.
func (m *MockFollowRepository) InactiveFollowRelation(ctx context.Context, follower, followee int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InactiveFollowRelation", ctx, follower, followee)
	ret0, _ := ret[0].(error)
	return ret0
}

// InactiveFollowRelation indicates an expected call of InactiveFollowRelation.
func (mr *MockFollowRepositoryMockRecorder) InactiveFollowRelation(ctx, follower, followee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InactiveFollowRelation", reflect.TypeOf((*MockFollowRepository)(nil).InactiveFollowRelation), ctx, follower, followee)
}
