syntax = "proto3";

package follow.v1;
option go_package = "follow/v1;followv1";

message FollowRelation {
    int64 id = 1;
    int64 follower = 2;
    int64 followee = 3; 
}

service FollowService {
    rpc Follow(FollowRequest) returns (FollowResponse);
    rpc CancelFollow(CancelFollowRequest) returns (CancelFollowResponse);
    rpc GetFollowee(GetFolloweeRequest) returns (GetFolloweeResponse);  // 获取某个人的关注列表
    rpc FollowInfo(FollowInfoRequest) returns (FollowInfoResponse);     // 获取某个人关注另一个人的详细信息
}

message GetFolloweeRequest {
    int64 follower = 1;
    int64 offset = 2;
    int64 limit = 3;
}

message GetFolloweeResponse {
    repeated FollowRelation follow_relations = 1;
}

message FollowInfoRequest {
    int64 follower = 1;
    int64 followee = 2;
}

message FollowInfoResponse {
    FollowRelation follow_relation = 1;
}

message FollowRequest {
    int64 followee = 1;
    int64 follower = 2;
}

message FollowResponse {
}

message CancelFollowRequest {
    int64 followee = 1;
    int64 follower = 2;
}

message CancelFollowResponse {
}