// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/payment/grpc"
	"webook/payment/ioc"
	"webook/payment/repository"
	"webook/payment/repository/dao"
	"webook/payment/web"
	"webook/pkg_local/wego"
)

// Injectors from wire.go:

func InitApp() *wego.App {
	wechatConfig := ioc.InitWechatConfig()
	handler := ioc.InitWechatNotifyHandler(wechatConfig)
	client := ioc.InitWechatClient(wechatConfig)
	db := ioc.InitDB()
	paymentDAO := dao.NewPaymentGormDAO(db)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	saramaClient := ioc.InitKafka()
	producer := ioc.InitProducer(saramaClient)
	logger := ioc.InitLogger()
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, producer, logger, wechatConfig)
	wechatHandler := web.NewWechatHandler(handler, nativePaymentService, logger)
	server := ioc.InitGinServer(wechatHandler)
	wechatServiceServer := grpc.NewWechatServiceServer(nativePaymentService)
	clientv3Client := ioc.InitEtcdClient()
	grpcxServer := ioc.InitGrpcServer(wechatServiceServer, clientv3Client, logger)
	app := &wego.App{
		WebServer:  server,
		GRPCServer: grpcxServer,
	}
	return app
}
