// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/account/grpc"
	"webook/account/ioc"
	"webook/account/repository"
	"webook/account/repository/cache"
	"webook/account/repository/dao"
	"webook/account/service"
	"webook/pkg_local/wego"
)

// Injectors from wire.go:

func Init() *wego.App {
	db := ioc.InitDB()
	accountDAO := dao.NewCreditGormDAO(db)
	cmdable := ioc.InitRedis()
	accountCache := cache.NewAccountRedisCache(cmdable)
	accountRepository := repository.NewAccountRepository(accountDAO, accountCache)
	logger := ioc.InitLogger()
	accountService := service.NewAccountService(accountRepository, logger)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(accountServiceServer, client, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}
