// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/reward/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockRewardRepository is a mock of RewardRepository interface.
type MockRewardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRewardRepositoryMockRecorder
}

// MockRewardRepositoryMockRecorder is the mock recorder for MockRewardRepository.
type MockRewardRepositoryMockRecorder struct {
	mock *MockRewardRepository
}

// NewMockRewardRepository creates a new mock instance.
func NewMockRewardRepository(ctrl *gomock.Controller) *MockRewardRepository {
	mock := &MockRewardRepository{ctrl: ctrl}
	mock.recorder = &MockRewardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardRepository) EXPECT() *MockRewardRepositoryMockRecorder {
	return m.recorder
}

// CachedCodeURL mocks base method.
func (m *MockRewardRepository) CachedCodeURL(ctx context.Context, cu domain.CodeURL, r domain.Reward) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachedCodeURL", ctx, cu, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// CachedCodeURL indicates an expected call of CachedCodeURL.
func (mr *MockRewardRepositoryMockRecorder) CachedCodeURL(ctx, cu, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachedCodeURL", reflect.TypeOf((*MockRewardRepository)(nil).CachedCodeURL), ctx, cu, r)
}

// CreateReward mocks base method.
func (m *MockRewardRepository) CreateReward(ctx context.Context, reward domain.Reward) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReward", ctx, reward)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReward indicates an expected call of CreateReward.
func (mr *MockRewardRepositoryMockRecorder) CreateReward(ctx, reward interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReward", reflect.TypeOf((*MockRewardRepository)(nil).CreateReward), ctx, reward)
}

// GetCachedCodeURL mocks base method.
func (m *MockRewardRepository) GetCachedCodeURL(ctx context.Context, r domain.Reward) (domain.CodeURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedCodeURL", ctx, r)
	ret0, _ := ret[0].(domain.CodeURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedCodeURL indicates an expected call of GetCachedCodeURL.
func (mr *MockRewardRepositoryMockRecorder) GetCachedCodeURL(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedCodeURL", reflect.TypeOf((*MockRewardRepository)(nil).GetCachedCodeURL), ctx, r)
}

// GetReward mocks base method.
func (m *MockRewardRepository) GetReward(ctx context.Context, rid int64) (domain.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReward", ctx, rid)
	ret0, _ := ret[0].(domain.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReward indicates an expected call of GetReward.
func (mr *MockRewardRepositoryMockRecorder) GetReward(ctx, rid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReward", reflect.TypeOf((*MockRewardRepository)(nil).GetReward), ctx, rid)
}

// UpdateStatus mocks base method.
func (m *MockRewardRepository) UpdateStatus(ctx context.Context, rid int64, status domain.RewardStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, rid, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRewardRepositoryMockRecorder) UpdateStatus(ctx, rid, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRewardRepository)(nil).UpdateStatus), ctx, rid, status)
}
