// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/account/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountDAO is a mock of AccountDAO interface.
type MockAccountDAO struct {
	ctrl     *gomock.Controller
	recorder *MockAccountDAOMockRecorder
}

// MockAccountDAOMockRecorder is the mock recorder for MockAccountDAO.
type MockAccountDAOMockRecorder struct {
	mock *MockAccountDAO
}

// NewMockAccountDAO creates a new mock instance.
func NewMockAccountDAO(ctrl *gomock.Controller) *MockAccountDAO {
	mock := &MockAccountDAO{ctrl: ctrl}
	mock.recorder = &MockAccountDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountDAO) EXPECT() *MockAccountDAOMockRecorder {
	return m.recorder
}

// AddActivities mocks base method.
func (m *MockAccountDAO) AddActivities(ctx context.Context, activities ...dao.AccountActivity) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range activities {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddActivities", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddActivities indicates an expected call of AddActivities.
func (mr *MockAccountDAOMockRecorder) AddActivities(ctx interface{}, activities ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, activities...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddActivities", reflect.TypeOf((*MockAccountDAO)(nil).AddActivities), varargs...)
}
