// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/article/events"
	"webook/article/grpc"
	"webook/article/ioc"
	"webook/article/repository"
	"webook/article/repository/cache"
	"webook/article/repository/dao"
	"webook/article/service"
	"webook/pkg_local/wego"
)

// Injectors from wire.go:

func Init() *wego.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	articleDAO := dao.NewGormArticleDAO(db)
	cmdable := ioc.InitRedis()
	articleCache := cache.NewArticleRedisCache(cmdable)
	articleRepository := repository.NewArticleRepository(articleDAO, articleCache, logger)
	userServiceClient := ioc.InitUserRpcClient()
	authorRepository := repository.NewGrpcAuthorRepository(userServiceClient, articleDAO)
	syncProducer := ioc.InitProducer()
	producer := events.NewSaramaSyncProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, authorRepository, logger, producer)
	articleServiceServer := grpc.NewArticleServiceServer(articleService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(articleServiceServer, client, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitLogger, ioc.InitUserRpcClient, ioc.InitProducer, ioc.InitEtcdClient, ioc.InitDB)
