// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	domain "webook/feed/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// CreateFeedEvent mocks base method.
func (m *MockFeedService) CreateFeedEvent(ctx context.Context, feed domain.FeedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeedEvent", ctx, feed)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFeedEvent indicates an expected call of CreateFeedEvent.
func (mr *MockFeedServiceMockRecorder) CreateFeedEvent(ctx, feed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeedEvent", reflect.TypeOf((*MockFeedService)(nil).CreateFeedEvent), ctx, feed)
}

// GetFeedEventList mocks base method.
func (m *MockFeedService) GetFeedEventList(ctx context.Context, uid, timestamp int64, limit int) ([]domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedEventList", ctx, uid, timestamp, limit)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedEventList indicates an expected call of GetFeedEventList.
func (mr *MockFeedServiceMockRecorder) GetFeedEventList(ctx, uid, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedEventList", reflect.TypeOf((*MockFeedService)(nil).GetFeedEventList), ctx, uid, timestamp, limit)
}

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// CreateFeedEvent mocks base method.
func (m *MockHandler) CreateFeedEvent(ctx context.Context, ext domain.ExtendFields) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeedEvent", ctx, ext)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFeedEvent indicates an expected call of CreateFeedEvent.
func (mr *MockHandlerMockRecorder) CreateFeedEvent(ctx, ext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeedEvent", reflect.TypeOf((*MockHandler)(nil).CreateFeedEvent), ctx, ext)
}

// FindFeedEvents mocks base method.
func (m *MockHandler) FindFeedEvents(ctx context.Context, uid, timestamp int64, limit int) ([]domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFeedEvents", ctx, uid, timestamp, limit)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFeedEvents indicates an expected call of FindFeedEvents.
func (mr *MockHandlerMockRecorder) FindFeedEvents(ctx, uid, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFeedEvents", reflect.TypeOf((*MockHandler)(nil).FindFeedEvents), ctx, uid, timestamp, limit)
}
