// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/search/events"
	"webook/search/grpc"
	"webook/search/ioc"
	"webook/search/repository"
	"webook/search/repository/dao"
	"webook/search/service"
)

// Injectors from wire.go:

func Init() *App {
	client := ioc.InitESClient()
	userDAO := dao.NewUserElasticSearchDAO(client)
	userRepository := repository.NewUserRepository(userDAO)
	articleDAO := dao.NewArticleElasticSearchDAO(client)
	tagDAO := dao.NewTagElasticSearchDAO(client)
	articleRepository := repository.NewArticleRepository(articleDAO, tagDAO)
	anyDAO := dao.NewAnyElasticSearchDAO(client)
	anyRepository := repository.NewAnyRepository(anyDAO)
	syncService := service.NewSyncService(userRepository, articleRepository, anyRepository)
	syncServiceServer := grpc.NewSyncServiceServer(syncService)
	searchService := service.NewSearchService(userRepository, articleRepository)
	searchServiceServer := grpc.NewSearchServiceServer(searchService)
	clientv3Client := ioc.InitEtcdClient()
	logger := ioc.InitLogger()
	server := ioc.InitGrpcxServer(syncServiceServer, searchServiceServer, clientv3Client, logger)
	saramaClient := ioc.InitKafka()
	articleConsumer := events.NewArticleConsumer(syncService, saramaClient, logger)
	userConsumer := events.NewUserConsumer(syncService, saramaClient, logger)
	v := ioc.NewConsumers(articleConsumer, userConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var svcProviderSet = wire.NewSet(dao.NewUserElasticSearchDAO, dao.NewArticleElasticSearchDAO, dao.NewAnyElasticSearchDAO, dao.NewTagElasticSearchDAO, repository.NewUserRepository, repository.NewArticleRepository, repository.NewAnyRepository, service.NewSyncService, service.NewSearchService)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitESClient, ioc.InitEtcdClient, ioc.InitKafka)
