// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/payment/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockLocalMsgRepository is a mock of LocalMsgRepository interface.
type MockLocalMsgRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocalMsgRepositoryMockRecorder
}

// MockLocalMsgRepositoryMockRecorder is the mock recorder for MockLocalMsgRepository.
type MockLocalMsgRepositoryMockRecorder struct {
	mock *MockLocalMsgRepository
}

// NewMockLocalMsgRepository creates a new mock instance.
func NewMockLocalMsgRepository(ctrl *gomock.Controller) *MockLocalMsgRepository {
	mock := &MockLocalMsgRepository{ctrl: ctrl}
	mock.recorder = &MockLocalMsgRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalMsgRepository) EXPECT() *MockLocalMsgRepositoryMockRecorder {
	return m.recorder
}

// AddMsg mocks base method.
func (m *MockLocalMsgRepository) AddMsg(ctx context.Context, content string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMsg", ctx, content)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMsg indicates an expected call of AddMsg.
func (mr *MockLocalMsgRepositoryMockRecorder) AddMsg(ctx, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMsg", reflect.TypeOf((*MockLocalMsgRepository)(nil).AddMsg), ctx, content)
}

// FindInitMsg mocks base method.
func (m *MockLocalMsgRepository) FindInitMsg(ctx context.Context, limit, offset int) ([]domain.Msg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInitMsg", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.Msg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInitMsg indicates an expected call of FindInitMsg.
func (mr *MockLocalMsgRepositoryMockRecorder) FindInitMsg(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInitMsg", reflect.TypeOf((*MockLocalMsgRepository)(nil).FindInitMsg), ctx, limit, offset)
}

// MarkFailed mocks base method.
func (m *MockLocalMsgRepository) MarkFailed(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockLocalMsgRepositoryMockRecorder) MarkFailed(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockLocalMsgRepository)(nil).MarkFailed), ctx, id)
}

// MarkSuccess mocks base method.
func (m *MockLocalMsgRepository) MarkSuccess(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSuccess", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSuccess indicates an expected call of MarkSuccess.
func (mr *MockLocalMsgRepositoryMockRecorder) MarkSuccess(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSuccess", reflect.TypeOf((*MockLocalMsgRepository)(nil).MarkSuccess), ctx, id)
}
