// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/oauth2/grpc"
	"webook/oauth2/ioc"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	service := ioc.InitPrometheus(logger)
	oauth2ServiceServer := grpc.NewOauth2ServiceServer(service)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(oauth2ServiceServer, client, logger)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitEtcdClient)
