// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/pkg_local/wego"
	"webook/sms/grpc"
	"webook/sms/ioc"
)

// Injectors from wire.go:

func Init() *wego.App {
	service := ioc.InitSmsMemoryService()
	smsServiceServer := grpc.NewSmsServiceServer(service)
	client := ioc.InitEtcdClient()
	logger := ioc.InitLogger()
	server := ioc.InitGrpcxServer(smsServiceServer, client, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}
