// Code generated by MockGen. DO NOT EDIT.
// Source: ./feed_push_event.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/feed/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockFeedPushEventDAO is a mock of FeedPushEventDAO interface.
type MockFeedPushEventDAO struct {
	ctrl     *gomock.Controller
	recorder *MockFeedPushEventDAOMockRecorder
}

// MockFeedPushEventDAOMockRecorder is the mock recorder for MockFeedPushEventDAO.
type MockFeedPushEventDAOMockRecorder struct {
	mock *MockFeedPushEventDAO
}

// NewMockFeedPushEventDAO creates a new mock instance.
func NewMockFeedPushEventDAO(ctrl *gomock.Controller) *MockFeedPushEventDAO {
	mock := &MockFeedPushEventDAO{ctrl: ctrl}
	mock.recorder = &MockFeedPushEventDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedPushEventDAO) EXPECT() *MockFeedPushEventDAOMockRecorder {
	return m.recorder
}

// CreatePushEvent mocks base method.
func (m *MockFeedPushEventDAO) CreatePushEvent(ctx context.Context, events []dao.FeedPushEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePushEvent", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePushEvent indicates an expected call of CreatePushEvent.
func (mr *MockFeedPushEventDAOMockRecorder) CreatePushEvent(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePushEvent", reflect.TypeOf((*MockFeedPushEventDAO)(nil).CreatePushEvent), ctx, events)
}

// GetPushEvents mocks base method.
func (m *MockFeedPushEventDAO) GetPushEvents(ctx context.Context, uid, timestamp int64, limit int) ([]dao.FeedPushEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushEvents", ctx, uid, timestamp, limit)
	ret0, _ := ret[0].([]dao.FeedPushEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushEvents indicates an expected call of GetPushEvents.
func (mr *MockFeedPushEventDAOMockRecorder) GetPushEvents(ctx, uid, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushEvents", reflect.TypeOf((*MockFeedPushEventDAO)(nil).GetPushEvents), ctx, uid, timestamp, limit)
}

// GetPushEventsWithType mocks base method.
func (m *MockFeedPushEventDAO) GetPushEventsWithType(ctx context.Context, _type string, uid, timestamp int64, limit int) ([]dao.FeedPushEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushEventsWithType", ctx, _type, uid, timestamp, limit)
	ret0, _ := ret[0].([]dao.FeedPushEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushEventsWithType indicates an expected call of GetPushEventsWithType.
func (mr *MockFeedPushEventDAOMockRecorder) GetPushEventsWithType(ctx, _type, uid, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushEventsWithType", reflect.TypeOf((*MockFeedPushEventDAO)(nil).GetPushEventsWithType), ctx, _type, uid, timestamp, limit)
}
