// Code generated by MockGen. DO NOT EDIT.
// Source: ./feed_pull_event.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/feed/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockFeedPullEventDAO is a mock of FeedPullEventDAO interface.
type MockFeedPullEventDAO struct {
	ctrl     *gomock.Controller
	recorder *MockFeedPullEventDAOMockRecorder
}

// MockFeedPullEventDAOMockRecorder is the mock recorder for MockFeedPullEventDAO.
type MockFeedPullEventDAOMockRecorder struct {
	mock *MockFeedPullEventDAO
}

// NewMockFeedPullEventDAO creates a new mock instance.
func NewMockFeedPullEventDAO(ctrl *gomock.Controller) *MockFeedPullEventDAO {
	mock := &MockFeedPullEventDAO{ctrl: ctrl}
	mock.recorder = &MockFeedPullEventDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedPullEventDAO) EXPECT() *MockFeedPullEventDAOMockRecorder {
	return m.recorder
}

// CreatePullEvent mocks base method.
func (m *MockFeedPullEventDAO) CreatePullEvent(ctx context.Context, event dao.FeedPullEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePullEvent indicates an expected call of CreatePullEvent.
func (mr *MockFeedPullEventDAOMockRecorder) CreatePullEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullEvent", reflect.TypeOf((*MockFeedPullEventDAO)(nil).CreatePullEvent), ctx, event)
}

// FindPullEventList mocks base method.
func (m *MockFeedPullEventDAO) FindPullEventList(ctx context.Context, uids []int64, timestamp int64, limit int) ([]dao.FeedPullEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullEventList", ctx, uids, timestamp, limit)
	ret0, _ := ret[0].([]dao.FeedPullEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullEventList indicates an expected call of FindPullEventList.
func (mr *MockFeedPullEventDAOMockRecorder) FindPullEventList(ctx, uids, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullEventList", reflect.TypeOf((*MockFeedPullEventDAO)(nil).FindPullEventList), ctx, uids, timestamp, limit)
}

// FindPullEventListWithType mocks base method.
func (m *MockFeedPullEventDAO) FindPullEventListWithType(ctx context.Context, _type string, uids []int64, timestamp int64, limit int) ([]dao.FeedPullEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullEventListWithType", ctx, _type, uids, timestamp, limit)
	ret0, _ := ret[0].([]dao.FeedPullEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullEventListWithType indicates an expected call of FindPullEventListWithType.
func (mr *MockFeedPullEventDAOMockRecorder) FindPullEventListWithType(ctx, _type, uids, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullEventListWithType", reflect.TypeOf((*MockFeedPullEventDAO)(nil).FindPullEventListWithType), ctx, _type, uids, timestamp, limit)
}
