// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAnyDAO is a mock of AnyDAO interface.
type MockAnyDAO struct {
	ctrl     *gomock.Controller
	recorder *MockAnyDAOMockRecorder
}

// MockAnyDAOMockRecorder is the mock recorder for MockAnyDAO.
type MockAnyDAOMockRecorder struct {
	mock *MockAnyDAO
}

// NewMockAnyDAO creates a new mock instance.
func NewMockAnyDAO(ctrl *gomock.Controller) *MockAnyDAO {
	mock := &MockAnyDAO{ctrl: ctrl}
	mock.recorder = &MockAnyDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnyDAO) EXPECT() *MockAnyDAOMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAnyDAO) Delete(ctx context.Context, index, docId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, index, docId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAnyDAOMockRecorder) Delete(ctx, index, docId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAnyDAO)(nil).Delete), ctx, index, docId)
}

// Input mocks base method.
func (m *MockAnyDAO) Input(ctx context.Context, index, docId, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Input", ctx, index, docId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Input indicates an expected call of Input.
func (mr *MockAnyDAOMockRecorder) Input(ctx, index, docId, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Input", reflect.TypeOf((*MockAnyDAO)(nil).Input), ctx, index, docId, data)
}