// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCollectDAO is a mock of CollectDAO interface.
type MockCollectDAO struct {
	ctrl     *gomock.Controller
	recorder *MockCollectDAOMockRecorder
}

// MockCollectDAOMockRecorder is the mock recorder for MockCollectDAO.
type MockCollectDAOMockRecorder struct {
	mock *MockCollectDAO
}

// NewMockCollectDAO creates a new mock instance.
func NewMockCollectDAO(ctrl *gomock.Controller) *MockCollectDAO {
	mock := &MockCollectDAO{ctrl: ctrl}
	mock.recorder = &MockCollectDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectDAO) EXPECT() *MockCollectDAOMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockCollectDAO) Search(ctx context.Context, uid int64, biz string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, uid, biz)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockCollectDAOMockRecorder) Search(ctx, uid, biz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCollectDAO)(nil).Search), ctx, uid, biz)
}
