// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLikeDAO is a mock of LikeDAO interface.
type MockLikeDAO struct {
	ctrl     *gomock.Controller
	recorder *MockLikeDAOMockRecorder
}

// MockLikeDAOMockRecorder is the mock recorder for MockLikeDAO.
type MockLikeDAOMockRecorder struct {
	mock *MockLikeDAO
}

// NewMockLikeDAO creates a new mock instance.
func NewMockLikeDAO(ctrl *gomock.Controller) *MockLikeDAO {
	mock := &MockLikeDAO{ctrl: ctrl}
	mock.recorder = &MockLikeDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeDAO) EXPECT() *MockLikeDAOMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockLikeDAO) Search(ctx context.Context, uid int64, biz string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, uid, biz)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockLikeDAOMockRecorder) Search(ctx, uid, biz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockLikeDAO)(nil).Search), ctx, uid, biz)
}
