// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTagDAO is a mock of TagDAO interface.
type MockTagDAO struct {
	ctrl     *gomock.Controller
	recorder *MockTagDAOMockRecorder
}

// MockTagDAOMockRecorder is the mock recorder for MockTagDAO.
type MockTagDAOMockRecorder struct {
	mock *MockTagDAO
}

// NewMockTagDAO creates a new mock instance.
func NewMockTagDAO(ctrl *gomock.Controller) *MockTagDAO {
	mock := &MockTagDAO{ctrl: ctrl}
	mock.recorder = &MockTagDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagDAO) EXPECT() *MockTagDAOMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockTagDAO) Search(ctx context.Context, uid int64, biz string, keywords []string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, uid, biz, keywords)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockTagDAOMockRecorder) Search(ctx, uid, biz, keywords interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockTagDAO)(nil).Search), ctx, uid, biz, keywords)
}
