syntax = "proto3";

package reward.v1;
option go_package = "reward/v1;rewardv1";

service RewardService {
    rpc PreReward(PreRewardRequest) returns (PreRewardResponse);
    rpc GetReward(GetRewardRequest) returns (GetRewardResponse);
}

message GetRewardRequest {
    int64 rid = 1;
    int64 uid = 2;
}

message GetRewardResponse {
    RewardStatus status = 1;
}

enum RewardStatus {
    RewardStatusUnknown = 0;
    RewardStatusInit = 1;
    RewardStatusPayed = 2;
    RewardStatusFailed = 3;
}

message PreRewardRequest {
    string biz = 1;
    int64 biz_id = 2;
    string biz_name = 3;
    int64 target_uid = 4;
    int64 uid = 5;
    int64 amt = 6;
}

message PreRewardResponse {
    string code_url = 1;
    int64 rid = 2;
}