CREATE DATABASE IF NOT EXISTS webook;
CREATE DATABASE IF NOT EXISTS webook_account;
CREATE DATABASE IF NOT EXISTS webook_comment;
CREATE DATABASE IF NOT EXISTS webook_follow;
CREATE DATABASE IF NOT EXISTS webook_intr;
CREATE DATABASE IF NOT EXISTS webook_payment;
CREATE DATABASE IF NOT EXISTS webook_reward;
CREATE DATABASE IF NOT EXISTS webook;
CREATE DATABASE IF NOT EXISTS webook_tag;

CREATE USER 'canal'@'%' IDENTIFIED BY 'canal';
GRANT ALL PRIVILEGES ON *.* TO 'canal'@'%' WITH GRANT OPTION;