// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAnyRepository is a mock of AnyRepository interface.
type MockAnyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnyRepositoryMockRecorder
}

// MockAnyRepositoryMockRecorder is the mock recorder for MockAnyRepository.
type MockAnyRepositoryMockRecorder struct {
	mock *MockAnyRepository
}

// NewMockAnyRepository creates a new mock instance.
func NewMockAnyRepository(ctrl *gomock.Controller) *MockAnyRepository {
	mock := &MockAnyRepository{ctrl: ctrl}
	mock.recorder = &MockAnyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnyRepository) EXPECT() *MockAnyRepositoryMockRecorder {
	return m.recorder
}

// Input mocks base method.
func (m *MockAnyRepository) Input(ctx context.Context, index, docId, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Input", ctx, index, docId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Input indicates an expected call of Input.
func (mr *MockAnyRepositoryMockRecorder) Input(ctx, index, docId, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Input", reflect.TypeOf((*MockAnyRepository)(nil).Input), ctx, index, docId, data)
}
