// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/search/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockArticleRepository is a mock of ArticleRepository interface.
type MockArticleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepositoryMockRecorder
}

// MockArticleRepositoryMockRecorder is the mock recorder for MockArticleRepository.
type MockArticleRepositoryMockRecorder struct {
	mock *MockArticleRepository
}

// NewMockArticleRepository creates a new mock instance.
func NewMockArticleRepository(ctrl *gomock.Controller) *MockArticleRepository {
	mock := &MockArticleRepository{ctrl: ctrl}
	mock.recorder = &MockArticleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepository) EXPECT() *MockArticleRepositoryMockRecorder {
	return m.recorder
}

// InputArticle mocks base method.
func (m *MockArticleRepository) InputArticle(ctx context.Context, msg domain.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputArticle", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InputArticle indicates an expected call of InputArticle.
func (mr *MockArticleRepositoryMockRecorder) InputArticle(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputArticle", reflect.TypeOf((*MockArticleRepository)(nil).InputArticle), ctx, msg)
}

// SearchArticle mocks base method.
func (m *MockArticleRepository) SearchArticle(ctx context.Context, uid int64, keywords []string) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchArticle", ctx, uid, keywords)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchArticle indicates an expected call of SearchArticle.
func (mr *MockArticleRepositoryMockRecorder) SearchArticle(ctx, uid, keywords interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArticle", reflect.TypeOf((*MockArticleRepository)(nil).SearchArticle), ctx, uid, keywords)
}
