// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/search/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// InputUser mocks base method.
func (m *MockUserRepository) InputUser(ctx context.Context, msg domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputUser", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InputUser indicates an expected call of InputUser.
func (mr *MockUserRepositoryMockRecorder) InputUser(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputUser", reflect.TypeOf((*MockUserRepository)(nil).InputUser), ctx, msg)
}

// SearchUser mocks base method.
func (m *MockUserRepository) SearchUser(ctx context.Context, keywords []string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUser", ctx, keywords)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUser indicates an expected call of SearchUser.
func (mr *MockUserRepositoryMockRecorder) SearchUser(ctx, keywords interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUser", reflect.TypeOf((*MockUserRepository)(nil).SearchUser), ctx, keywords)
}
