// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"
	domain "webook/account/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountCache is a mock of AccountCache interface.
type MockAccountCache struct {
	ctrl     *gomock.Controller
	recorder *MockAccountCacheMockRecorder
}

// MockAccountCacheMockRecorder is the mock recorder for MockAccountCache.
type MockAccountCacheMockRecorder struct {
	mock *MockAccountCache
}

// NewMockAccountCache creates a new mock instance.
func NewMockAccountCache(ctrl *gomock.Controller) *MockAccountCache {
	mock := &MockAccountCache{ctrl: ctrl}
	mock.recorder = &MockAccountCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountCache) EXPECT() *MockAccountCacheMockRecorder {
	return m.recorder
}

// GetUnique mocks base method.
func (m *MockAccountCache) GetUnique(ctx context.Context, cr domain.Credit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnique", ctx, cr)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUnique indicates an expected call of GetUnique.
func (mr *MockAccountCacheMockRecorder) GetUnique(ctx, cr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnique", reflect.TypeOf((*MockAccountCache)(nil).GetUnique), ctx, cr)
}

// SetUnique mocks base method.
func (m *MockAccountCache) SetUnique(ctx context.Context, cr domain.Credit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUnique", ctx, cr)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUnique indicates an expected call of SetUnique.
func (mr *MockAccountCacheMockRecorder) SetUnique(ctx, cr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUnique", reflect.TypeOf((*MockAccountCache)(nil).SetUnique), ctx, cr)
}
