// Code generated by MockGen. DO NOT EDIT.
// Source: ./feed_event.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/feed/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockFeedEventRepository is a mock of FeedEventRepository interface.
type MockFeedEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedEventRepositoryMockRecorder
}

// MockFeedEventRepositoryMockRecorder is the mock recorder for MockFeedEventRepository.
type MockFeedEventRepositoryMockRecorder struct {
	mock *MockFeedEventRepository
}

// NewMockFeedEventRepository creates a new mock instance.
func NewMockFeedEventRepository(ctrl *gomock.Controller) *MockFeedEventRepository {
	mock := &MockFeedEventRepository{ctrl: ctrl}
	mock.recorder = &MockFeedEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedEventRepository) EXPECT() *MockFeedEventRepositoryMockRecorder {
	return m.recorder
}

// CreatePullEvent mocks base method.
func (m *MockFeedEventRepository) CreatePullEvent(ctx context.Context, events domain.FeedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullEvent", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePullEvent indicates an expected call of CreatePullEvent.
func (mr *MockFeedEventRepositoryMockRecorder) CreatePullEvent(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullEvent", reflect.TypeOf((*MockFeedEventRepository)(nil).CreatePullEvent), ctx, events)
}

// CreatePushEvents mocks base method.
func (m *MockFeedEventRepository) CreatePushEvents(ctx context.Context, events []domain.FeedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePushEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePushEvents indicates an expected call of CreatePushEvents.
func (mr *MockFeedEventRepositoryMockRecorder) CreatePushEvents(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePushEvents", reflect.TypeOf((*MockFeedEventRepository)(nil).CreatePushEvents), ctx, events)
}

// FindPullEvents mocks base method.
func (m *MockFeedEventRepository) FindPullEvents(ctx context.Context, uids []int64, timestamp int64, limit int) ([]domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullEvents", ctx, uids, timestamp, limit)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullEvents indicates an expected call of FindPullEvents.
func (mr *MockFeedEventRepositoryMockRecorder) FindPullEvents(ctx, uids, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullEvents", reflect.TypeOf((*MockFeedEventRepository)(nil).FindPullEvents), ctx, uids, timestamp, limit)
}

// FindPullEventsWithType mocks base method.
func (m *MockFeedEventRepository) FindPullEventsWithType(ctx context.Context, _type string, uids []int64, timestamp int64, limit int) ([]domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPullEventsWithType", ctx, _type, uids, timestamp, limit)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPullEventsWithType indicates an expected call of FindPullEventsWithType.
func (mr *MockFeedEventRepositoryMockRecorder) FindPullEventsWithType(ctx, _type, uids, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPullEventsWithType", reflect.TypeOf((*MockFeedEventRepository)(nil).FindPullEventsWithType), ctx, _type, uids, timestamp, limit)
}

// FindPushEvents mocks base method.
func (m *MockFeedEventRepository) FindPushEvents(ctx context.Context, uid, timestamp int64, limit int) ([]domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPushEvents", ctx, uid, timestamp, limit)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPushEvents indicates an expected call of FindPushEvents.
func (mr *MockFeedEventRepositoryMockRecorder) FindPushEvents(ctx, uid, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPushEvents", reflect.TypeOf((*MockFeedEventRepository)(nil).FindPushEvents), ctx, uid, timestamp, limit)
}

// FindPushEventsWithType mocks base method.
func (m *MockFeedEventRepository) FindPushEventsWithType(ctx context.Context, _type string, uid, timestamp int64, limit int) ([]domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPushEventsWithType", ctx, _type, uid, timestamp, limit)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPushEventsWithType indicates an expected call of FindPushEventsWithType.
func (mr *MockFeedEventRepositoryMockRecorder) FindPushEventsWithType(ctx, _type, uid, timestamp, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPushEventsWithType", reflect.TypeOf((*MockFeedEventRepository)(nil).FindPushEventsWithType), ctx, _type, uid, timestamp, limit)
}
