// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/feed/events"
	"webook/feed/grpc"
	"webook/feed/ioc"
	"webook/feed/repository"
	"webook/feed/repository/cache"
	"webook/feed/repository/dao"
	"webook/feed/service"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	db := ioc.InitDB()
	feedPullEventDAO := dao.NewFeedPullEventDAO(db)
	feedPushEventDAO := dao.NewFeedPushEventDAO(db)
	cmdable := ioc.InitRedis()
	feedEventCache := cache.NewFeedEventRedisCache(cmdable)
	feedEventRepository := repository.NewCachedFeedEventRepository(feedPullEventDAO, feedPushEventDAO, feedEventCache)
	followServiceClient := ioc.InitFollowClient()
	v := ioc.RegisterHandler(feedEventRepository, followServiceClient)
	feedService := service.NewFeedService(feedEventRepository, v, followServiceClient)
	feedServiceServer := grpc.NewFeedServiceServer(feedService)
	server := ioc.InitGrpcxServer(logger, client, feedServiceServer)
	saramaClient := ioc.InitKafka()
	articleEventConsumer := events.NewArticleEventConsumer(saramaClient, logger, feedService)
	feedEventConsumer := events.NewFeedEventConsumer(saramaClient, logger, feedService)
	v2 := ioc.NewConsumers(articleEventConsumer, feedEventConsumer)
	app := &App{
		server:    server,
		consumers: v2,
	}
	return app
}

// wire.go:

var svcProviderSet = wire.NewSet(dao.NewFeedPushEventDAO, dao.NewFeedPullEventDAO, cache.NewFeedEventRedisCache, repository.NewCachedFeedEventRepository)

var thirdProvider = wire.NewSet(ioc.InitEtcdClient, ioc.InitLogger, ioc.InitRedis, ioc.InitKafka, ioc.InitDB, ioc.InitFollowClient)
