// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/tag/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// BindTagToBiz mocks base method.
func (m *MockTagRepository) BindTagToBiz(ctx context.Context, uid int64, biz string, bizId int64, tags []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindTagToBiz", ctx, uid, biz, bizId, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindTagToBiz indicates an expected call of BindTagToBiz.
func (mr *MockTagRepositoryMockRecorder) BindTagToBiz(ctx, uid, biz, bizId, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindTagToBiz", reflect.TypeOf((*MockTagRepository)(nil).BindTagToBiz), ctx, uid, biz, bizId, tags)
}

// CreateTag mocks base method.
func (m *MockTagRepository) CreateTag(ctx context.Context, tag domain.Tag) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, tag)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockTagRepositoryMockRecorder) CreateTag(ctx, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockTagRepository)(nil).CreateTag), ctx, tag)
}

// GetBizTags mocks base method.
func (m *MockTagRepository) GetBizTags(ctx context.Context, uid int64, biz string, bizId int64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBizTags", ctx, uid, biz, bizId)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBizTags indicates an expected call of GetBizTags.
func (mr *MockTagRepositoryMockRecorder) GetBizTags(ctx, uid, biz, bizId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBizTags", reflect.TypeOf((*MockTagRepository)(nil).GetBizTags), ctx, uid, biz, bizId)
}

// GetTags mocks base method.
func (m *MockTagRepository) GetTags(ctx context.Context, uid int64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx, uid)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockTagRepositoryMockRecorder) GetTags(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockTagRepository)(nil).GetTags), ctx, uid)
}

// GetTagsById mocks base method.
func (m *MockTagRepository) GetTagsById(ctx context.Context, ids []int64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsById", ctx, ids)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsById indicates an expected call of GetTagsById.
func (mr *MockTagRepositoryMockRecorder) GetTagsById(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsById", reflect.TypeOf((*MockTagRepository)(nil).GetTagsById), ctx, ids)
}

// PreloadUserTags mocks base method.
func (m *MockTagRepository) PreloadUserTags(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreloadUserTags", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreloadUserTags indicates an expected call of PreloadUserTags.
func (mr *MockTagRepositoryMockRecorder) PreloadUserTags(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreloadUserTags", reflect.TypeOf((*MockTagRepository)(nil).PreloadUserTags), ctx)
}
