// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/pkg_local/wego"
	"webook/user/grpc"
	"webook/user/ioc"
	"webook/user/repository"
	"webook/user/repository/cache"
	"webook/user/repository/dao"
	"webook/user/service"
)

// Injectors from wire.go:

func Init() *wego.App {
	db := ioc.InitDB()
	userDAO := dao.NewGormUserDAO(db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	logger := ioc.InitLogger()
	userRepository := repository.NewCachedUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(userRepository, logger)
	userServiceServer := grpc.NewUserServiceServer(userService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(userServiceServer, client, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitRedis, ioc.InitEtcdClient)
