// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/follow/grpc"
	"webook/follow/ioc"
	"webook/follow/repository"
	"webook/follow/repository/cache"
	"webook/follow/repository/dao"
	"webook/follow/service"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	followRelationDAO := dao.NewFollowRelationGormDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewFollowRedisCache(cmdable)
	followRepository := repository.NewCachedFollowRepository(followRelationDAO, followCache, logger)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowRelationServiceServer(followRelationService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(followServiceServer, client, logger)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var svcProviderSet = wire.NewSet(cache.NewFollowRedisCache, dao.NewFollowRelationGormDAO, repository.NewCachedFollowRepository, service.NewFollowRelationService, grpc.NewFollowRelationServiceServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitEtcdClient, ioc.InitDB, ioc.InitRedis)
