// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/cronjob/grpc"
	"webook/cronjob/ioc"
	"webook/cronjob/repository"
	"webook/cronjob/repository/dao"
	"webook/cronjob/service"
)

// Injectors from wire.go:

func Init() *App {
	cronJobRepository := repository.NewPreemptJobRepository()
	logger := ioc.InitLogger()
	cronJobService := service.NewCronJobService(cronJobRepository, logger)
	cronJobServiceServer := grpc.NewCronJobServiceServer(cronJobService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGrpcxServer(cronJobServiceServer, client, logger)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var svcProviderSet = wire.NewSet(dao.NewGormJobDAO, repository.NewPreemptJobRepository, service.NewCronJobService)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitEtcdClient, ioc.InitLogger)
