// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "webook/account/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// AddCredit mocks base method.
func (m *MockAccountRepository) AddCredit(ctx context.Context, c domain.Credit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredit", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCredit indicates an expected call of AddCredit.
func (mr *MockAccountRepositoryMockRecorder) AddCredit(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredit", reflect.TypeOf((*MockAccountRepository)(nil).AddCredit), ctx, c)
}

// CheckUnique mocks base method.
func (m *MockAccountRepository) CheckUnique(ctx context.Context, c domain.Credit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUnique", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckUnique indicates an expected call of CheckUnique.
func (mr *MockAccountRepositoryMockRecorder) CheckUnique(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUnique", reflect.TypeOf((*MockAccountRepository)(nil).CheckUnique), ctx, c)
}

// SetUnique mocks base method.
func (m *MockAccountRepository) SetUnique(ctx context.Context, c domain.Credit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUnique", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUnique indicates an expected call of SetUnique.
func (mr *MockAccountRepositoryMockRecorder) SetUnique(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUnique", reflect.TypeOf((*MockAccountRepository)(nil).SetUnique), ctx, c)
}
