// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	dao "webook/reward/repository/dao"

	gomock "github.com/golang/mock/gomock"
)

// MockRewardDAO is a mock of RewardDAO interface.
type MockRewardDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRewardDAOMockRecorder
}

// MockRewardDAOMockRecorder is the mock recorder for MockRewardDAO.
type MockRewardDAOMockRecorder struct {
	mock *MockRewardDAO
}

// NewMockRewardDAO creates a new mock instance.
func NewMockRewardDAO(ctrl *gomock.Controller) *MockRewardDAO {
	mock := &MockRewardDAO{ctrl: ctrl}
	mock.recorder = &MockRewardDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardDAO) EXPECT() *MockRewardDAOMockRecorder {
	return m.recorder
}

// GetReward mocks base method.
func (m *MockRewardDAO) GetReward(ctx context.Context, rid int64) (dao.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReward", ctx, rid)
	ret0, _ := ret[0].(dao.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReward indicates an expected call of GetReward.
func (mr *MockRewardDAOMockRecorder) GetReward(ctx, rid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReward", reflect.TypeOf((*MockRewardDAO)(nil).GetReward), ctx, rid)
}

// Insert mocks base method.
func (m *MockRewardDAO) Insert(ctx context.Context, r dao.Reward) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockRewardDAOMockRecorder) Insert(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRewardDAO)(nil).Insert), ctx, r)
}

// UpdateStatus mocks base method.
func (m *MockRewardDAO) UpdateStatus(ctx context.Context, rid int64, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, rid, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRewardDAOMockRecorder) UpdateStatus(ctx, rid, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRewardDAO)(nil).UpdateStatus), ctx, rid, status)
}
